export class RegisterReview {
      profileId: any;
      registrationId: any;
      spgVersion: any;
      spgUpdateUser: any;
      registrationDate: any;
      registerTypeId: any;
      nextReviewDate: any;
      registrationProviderId: any;
      registeringTeam: any;
      registeringOfficer: any;
      registrationCategoryId: any;
      registrationLevelId: any;
      registrationNote: any;
      spgRegistrationId: any;
      createdBy: any;
      createdByUserId: any;
      createdDate: any;
      modifiedBy: any;
      modifiedByUserId: any;
      modifiedDate: any;
      deleted: any;
      deletedBy: any;
      deletedByUserId: any;
      deletedDate: any;
      locked: any;
      version: any;
      registerTypeFlagId: any;
      deregistrationDate: any;
      reviewPeriod: any;
      activeFlagId: any;
      familyName: any;
      firstName: any;
      caseManager: any;
      registrationReviewId: any;
      rrlocked: any;
      caseReferenceNumber: any;
      registerType:any;
      registerTypeFlag:any;
  }