export class ProcessContact {
       processId: any;
      profileId: any;
      spgVersion: any;
      spgUpdateUser: any;
      processTypeId: any;
      processSubTypeId: any;
      processRefDate: any;
      processExpectedStartDate: any;
      processStartDate: any;
      processExpectedEndDate: any;
      processEndDate: any;
      processStageId: any;
      processStageDate: any;
      processNote: any;
      processOutcomeId: any;
      processEndAttCount: any;
      intendedProviderId: any;
      spgProcessContactId: any;
      processManagerProviderId: any;
      createdBy: any;
      createdByUserId: any;
      createdDate: any;
      modifiedBy: any;
      modifiedByUserId: any;
      modifiedDate: any;
      deleted: any;
      deletedBy: any;
      deletedByUserId: any;
      deletedDate: any;
      locked: any;
      version: any;
      relatesTo: any;
      nsiTeam: any;
      nsiOfficer: any;
      documents: any;
     unitsCode : any;
     nsiOfficerId:any;
     nsiTeamId:any;
     length:any;
     isActive:any;
     isDelete:any;
  }