export class OffenderProfile {
	offenderDetailId: number;
	profileId: number;
	allowSmsYesNoId: string;
	dateDied: Date;
	dateOfBirth: Date;
	emailAddress: string;
	equalityMonitoringNote: string;
	ethnicityId: number;
	eventCount: number;
	exclusionMessage: string;
	exclusionsExistYesNoId: string;
	familyName: string;
	fileName: string;
	firstName: string;
	genderId: number;
	immigrationStatusId: number;
	interpreterRequiredYesNoId: string;
	languageId: number;
	mobileNumber: string;
	nationalityId: number;
	note: string;
	offenderManagerProviderId: number;
	offenderManagerResponsibleOfficer: string;
	offenderManagerResponsibleTeam: string;
	previousName: string;
	religionId: number;
	remandStatus: string;
	restrictionMessage: string;
	restrictionsExistYesNoId: string;
	secondName: string;
	secondNationalityId: number;
	sexualOrientationId: number;
	telephoneNumber: string;
	terminatedEventCount: number;
	thirdName: string;
	tierId: number;
	titleId: number;
	transGenderDiscloseConsentYesNoId: string;
	transGenderProcessId: number;
	transferPendingYesNoId: number;
	spgVersion: string;
	spgUpdateUser: string;
	createdDate: Date;
	createdBy: string;
	createdByUserId: number;
	modifiedDate: Date;
	modifiedBy: string;
	modifiedByUserId: number;
	deleted: number;
	deletedDate: Date;
	deletedBy: string;
	deletedByUserId: number;
	locked: number;
	version: number;
	offenderName: string;
	transferDate: Date;
	caseReferenceNumber: string;
	omTransferFromProvider: string;
	omTransferReason: string;
	isLao: string;

	croNumber: string;
	immigrationNumber: string;
	niNumber: string;
	nomsNumber: string;
	pncNumber: string;
	rsrDate: Date;
	rsrScore: string;

	caseReviewDate: Date
	reallocationDate: Date
	dateReleaseFromCustody: Date
	dateReturnedToCustody: Date
	referralDate: Date
	dependantsId: number
	domicileId: number
	caseManagerId: number
	preferredCommunicationMethodId: number
	providerId: number
	reviewingOfficerProviderId: number
	suitableGroupWorkYesNoId: number
	privateYesNoId: number
	reviewingOfficerTeamId: number
	serviceUserStateId: number
	serviceUserTypeId: number
	statusId: number
	teamId: number

  hasActiveRestrictions: any;
  hasActiveExclusions: any;
  notAuthorizedForCurrentUser: any;
}
