export class Contact {
       profileId: any;
      spgVersion: any;
      contactId: any;
      spgUpdateUser: any;
      contactStartTime: any;
      contactEndTime: any;
      note: any;
      location: any;
      relatesTo: any;
      spgContactId: any;
      createdBy: any;
      createdByUserId: any;
      createdDate: any;
      modifiedBy: any;
      modifiedByUserId: any;
      modifiedDate: any;
      deleted: any;
      deletedBy: any;
      deletedByUserId: any;
      deletedDate: any;
      locked: any;
      version: any;
      contactTypeId: any;
      contactDate: any;
      providerId: any;
      team: any;
      contactOfficer: any;
      contactOutcomeId: any;
      enforcementActionId: any;
      sensitiveContactYesNoId: any;
      alertYesNoId: any;
      contactCategoryId: any;
      rarDay:any;
      responseBy:any;
      contactType:any;
      dataId:any;
      tableId:any;
      fromDate: any;
      toDate: any;
      updatedByExternalOrg: any;
      // tableId:any;
      
  }