export const DocumentEntityFeatureConstants ={
    APREFFERAL: 31,
    REFERRAL: 20,
    CASE_ALLOCATION: 101,
    COURTREPORT: 27,
    INSTITUTIONALREPORT: 29,
    CONTACT: 35,
    OFFENDER: 2,
    PERSONALCONTACT: 9,
    EVENT: 14,
    ADDRESSASSESSMENT: 6,
    ASSESSMENT: 21,
    PROCESSCONTACT: 36,
    RATECARDINTERVENTION: 46,
    PERSONALCIRCUMSTANCE: 10
}