export class PssRequirement {
  profileId: any;
  pssRequirementId: any;
  eventId: any;
  spgVersion: any;
  spgUpdateUser: any;
  length: any;
  imposedDate: any;
  notes: any;
  expectedEndDate: any;
  actualEndDate: any;
  terminationReasonId: any;
  attendanceCount: any;
  psProviderId: any;
  psResponsibleTeam: any;
  psResponsibleOfficer: any;
  spgPssRequirementId: any;
  createdBy: any;
  createdByUserId: any;
  createdDate: any;
  modifiedBy: any;
  modifiedByUserId: any;
  modifiedDate: any;
  deleted: any;
  deletedBy: any;
  deletedByUserId: any;
  deletedDate: any;
  locked: any;
  version: any;
  pssRequirementTypeMainCategoryId: any;
  pssRequirementTypeSubCategoryId: any;
  expectedStartDate: any;
  actualStartDate: any;
  unitsCode : any;
}