export class ComponentManager {
	caseManagerAllocationId: number;
	endDate: Date;
	profileId: number;
	startDate: Date;
	teamId: number;
	userId: number;
	officeTeamId:number;
    officerId:number;
	dataId: number;
	descriptionId:number;
	transferReasonId:number;
	toProvider:number;
	tableId: number;
	transferRequestId: number;
	requestType: string;
	createdDate: Date;
	createdBy: string;
	createdByUserId: number;
	modifiedDate: Date;
	modifiedBy: string;
	modifiedByUserId: number;
	deleted: number;
	deletedDate: Date;
	deletedBy: string;
	deletedByUserId: number;
	locked: number;
	version: number;
	transferReponseId:number;
}
