export class Assessment {
       spgVersion: any;
       profileId: any;
      referralId: any;
      assessmentId: any;
      spgUpdateUser: any;
      assessmentProviderId: any;
      assessmentTeam: any;
      assessmentOfficer: any;
      assessmentScore: any;
      durationInMinutes: any;
      offenderAgreementYesNoId: any;
      spgAssessmentId: any;
      eventId: any;
      createdBy: any;
      createdByUserId: any;
      createdDate: any;
      modifiedBy: any;
      modifiedByUserId: any;
      modifiedDate: any;
      deleted: any;
      deletedBy: any;
      deletedByUserId: any;
      deletedDate: any;
      locked: any;
      version: any;
      assessmentDate: any;
      assessmentTypeId: any;
      offenderRequiredToAttendYesNoId: any;
      offenderAttendedYesNoId: any;
      assessmentOutcomeId: any;
      note: any;
      referralTypeId:any;
  }